# This workflow defines the CI/CD pipeline for the project.
# 1. CI (Continuous Integration): Runs tests on every push.
# 2. CD (Continuous Deployment): Deploys the application if tests pass.

name: CI/CD for Car Price Predictor

# Trigger the workflow on every push to the main branch
on:
  push:
    branches: [ "main", "master" ]

jobs:
  # ----------------------------------------------------
  # CI Job: Run tests to validate the model and code
  # ----------------------------------------------------
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi

      - name: Run model tests
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: python app/test_model.py

  # --------------------------------------------------------------------
  # CD Job: Build and push a Docker image if the 'test' job succeeds
  # --------------------------------------------------------------------
  deploy:
    # This job will only run if the 'test' job completes successfully
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          # The image will be named your-dockerhub-username/car-price-predictor:latest
          # IMPORTANT: Replace 'st126488' with your actual Docker Hub username.
          push: true
          tags: st126488/car-price-predictor:latest

